### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by jimmy1yoon** [jimmy1yoon/webscraper-jimmy#1]
TODO LIST
- [ ] `change_href()` -> 수집한 href url 중에서 이동 불가능한 url(script 로 이동하는 요소)을 outerHTML코드를 parsing하여 url 업데이트
- [ ] `get_html_elements()` -> a 태그 이외에 다른 원하는 tag(Ex: button)를 입력받아 함께 저장
- [ ] `get_logs()` -> 광고 매체별 request log 추출 / get method 이외에 post request 파라미터 추출
- [ ] Login 기능 추가 (Google Login은 selenium driver를 사용하면 이용 X, 현재는 사용자가 직접 ID, password를 입력하는 방식)
- [ ] `sql insert` -> 중복 Check -> 현재는 중복 check 없이 모든 row를 insert
